#!/bin/sh

# if refreshing bspwm, remove all previous rules to prevent doubling up
bspc rule -r "*"

if [ -x $HOME/.local/bin/dual_monitor ]; then
  dual_monitor
fi

# Starting up workspaces on both monitors
# TODO fix this using below loop and for multiple machines
bspc monitor eDP-1 -d 1 2 3 4
bspc monitor DP-1 -d 5 6 7 8
bspc monitor DP-3 -d 9 10 11 12
# bspc desktop -f I

# Look for a non-laptop monitor, and use it by default.
# If there's nothing else, we use the laptop screen (LVDS)
#mainmonitor="$(bspc query --monitors --names | grep -v eDP1 | head -n 1)"
#mainmonitor="$(bspc query --monitors --names)"
#if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
#    xrandr --output "$mainmonitor" --auto --output LVDS1 --off
#fi

bspc config border_width 3
bspc config window_gap 5
bspc config top_padding 23

# if you like having the focus follow wherever the cursor currently is,
# (not even where it last clicked), enable this. IMO it's super annoying
#bspc config focus_follows_pointer true

# config stuff that I'm unsure about
# bspc config split_ratio 0.52 # not sure what this does so commented out
bspc config borderless_monocle true
bspc config gapless_monocle true

# Use Wal's colors

#source "${HOME}/.cache/wal/colors.sh"
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

# window rules

# bspc rule -a Sxiv:\* state=floating

# Add swallowing
pgrep bspswallow || bspswallow &

# TODO
#    1) Add dropdown stuff
